const diaDanhBase = "/assets/dia-danh";
const trangAnBase = `${diaDanhBase}/trang-an`;
const hoaLuBase = `${diaDanhBase}/co-do-hoa-lu`;
const baiDinhBase = `${diaDanhBase}/bai-dinh`;
const tamCocBase = `${diaDanhBase}/tam-coc-bich-dong`;
const phoCoBase = `${diaDanhBase}/pho-co-hoa-lu`;
const hangMuaBase = `${diaDanhBase}/hang-mua`;

export const heritageDestinations = [
  {
    slug: "trang-an",
    layout: "trang-an",
    name: "Tràng An",
    navName: "TRÀNG AN",
    eyebrow: "Di sản văn hóa và thiên nhiên thế giới",
    title: "Tràng An - Hành trình giữa miền di sản ngàn năm",
    subtitle: "Nơi hội tụ vẻ đẹp của thiên nhiên, lịch sử và văn hóa Việt Nam.",
    heroImage: `${trangAnBase}/TA1.jpg`,
    featureImage: `${trangAnBase}/TA2.jpg`,
    storyImage1: "/assets/dia-danh-stories/trang-an-story-1.png",
    storyImage2: "/assets/dia-danh-stories/trang-an-story-2.png",
    featureCaption: "UNESCO vinh danh năm 2014 là di sản hỗn hợp đầu tiên tại Đông Nam Á.",
    sectionLabel: "Kỳ quan thiên nhiên",
    introTitle: "Vịnh Hạ Long trên cạn",
    introParagraphs: [
      "Được UNESCO công nhận là Di sản Văn hóa và Thiên nhiên Thế giới vào năm 2014, Tràng An là niềm tự hào của Ninh Bình và là di sản hỗn hợp đầu tiên của Việt Nam.",
      "Hàng triệu năm trước, nơi đây từng là vùng biển cổ rộng lớn. Sự biến đổi địa chất đã tạo nên quần thể núi đá vôi kỳ vĩ cùng hệ thống hang động xuyên thủy độc đáo.",
      "Những dãy núi xanh trùng điệp soi bóng xuống dòng nước trong vắt tạo nên khung cảnh được nhiều du khách gọi là Vịnh Hạ Long trên cạn.",
    ],
    storyTitle: "Dòng nước giữ ký ức cố đô",
    storyParagraphs: [
      "Tràng An không chỉ đẹp bởi thiên nhiên. Vùng đất này còn gắn liền với lịch sử hình thành và phát triển của kinh đô Hoa Lư xưa.",
      "Trong thời kỳ nhà Đinh và nhà Tiền Lê, núi đá vôi hiểm trở cùng hệ thống sông ngòi tự nhiên đã trở thành bức tường thành bảo vệ kinh đô đầu tiên của nước Đại Cồ Việt.",
      "Hành trình ngồi thuyền len lỏi qua Hang Sáng, Hang Tối, Hang Nấu Rượu hay Hang Địa Linh khiến du khách như bước vào một thế giới nơi con người và thiên nhiên hòa quyện.",
    ],
    highlights: [
      { number: "01", title: "Di sản kép", description: "Thiên nhiên, lịch sử và khảo cổ cùng hội tụ trong một quần thể hiếm có." },
      { number: "02", title: "Hang xuyên thủy", description: "Những dòng nước xanh nối các thung lũng đá vôi thành một hành trình liên hoàn." },
      { number: "03", title: "Khởi đầu hành trình", description: "Mỗi con thuyền và mỗi câu chuyện đều mở ra một dấu ấn của Sắc Cố Đô." },
    ],
    galleryEyebrow: "Góc nhìn di sản",
    galleryTitle: "Hành trình xuyên lòng núi",
    gallery: [
      { src: `${trangAnBase}/TA3.jpg`, caption: "Hang Sáng" },
      { src: `${trangAnBase}/TA4.jpg`, caption: "Kiến trúc cổ kính" },
      { src: `${trangAnBase}/TA5.jpg`, caption: "Sắc sen trên miền nước" },
      { src: `${trangAnBase}/TA8.jpg`, caption: "Dòng nước xanh giữa núi" },
      { src: `${trangAnBase}/TA10.jpg`, caption: "Bến thuyền Tràng An" },
      { src: `${trangAnBase}/TA12.jpg`, caption: "Núi đá vôi trùng điệp" },
    ],
    closingTitle: "Tìm lại vẻ bình yên trong trầm tích xanh",
    closingText: "Tràng An chào đón bạn bằng sự tĩnh lặng của núi và nhịp mái chèo khua nước nhẹ nhàng.",
  },
  {
    slug: "hoa-lu",
    layout: "hoa-lu",
    name: "Cố Đô Hoa Lư",
    navName: "HOA LƯ",
    eyebrow: "Hành trình đại cồ việt",
    title: "Cố Đô Hoa Lư - Nơi khởi nguồn của nước Đại Cồ Việt",
    subtitle: "Tòa kinh đô đầu tiên của Đại Cồ Việt nằm trong địa thế núi làm thành, sông làm hào.",
    heroImage: `${hoaLuBase}/CDHL 5.webp`,
    featureImage: `${hoaLuBase}/CĐHL 6.webp`,
    storyImage1: "/assets/dia-danh-stories/hoa-lu-story-1.png",
    storyImage2: "/assets/dia-danh-stories/hoa-lu-story-2.png",
    featureCaption: "Núi làm thành, sông làm hào - địa thế tự nhiên bảo vệ kinh đô xưa.",
    sectionLabel: "Di sản lịch sử",
    introTitle: "Núi làm thành, sông làm hào",
    introParagraphs: [
      "Ẩn mình giữa những dãy núi đá vôi hùng vĩ, Cố đô Hoa Lư là nơi lưu giữ dấu ấn đầu tiên của nhà nước phong kiến tập quyền Việt Nam.",
      "Hơn một nghìn năm trước, vua Đinh Tiên Hoàng chọn nơi đây làm kinh đô của nước Đại Cồ Việt, mở ra một giai đoạn mới trong lịch sử dựng nước.",
      "Nhờ địa thế núi làm thành, sông làm hào, Hoa Lư sở hữu vị trí phòng thủ tự nhiên vô cùng thuận lợi. Chính nơi đây đã chứng kiến sự ra đời của triều đại nhà Đinh, nhà Tiền Lê và những chiến công oanh liệt góp phần đặt nền móng cho quốc gia độc lập đầu tiên của Việt Nam.",
    ],
    storyTitle: "Lòng thành kính hướng về cội nguồn",
    storyParagraphs: [
      "Ngày nay, dù kinh đô đã chuyển về Thăng Long, dấu tích lịch sử vẫn hiện diện qua đền thờ vua Đinh Tiên Hoàng, đền vua Lê Đại Hành và nhiều công trình cổ kính.",
      "Bước qua từng cánh cổng đá rêu phong, du khách như quay ngược thời gian để lắng nghe câu chuyện về những vị anh hùng đã làm nên lịch sử.",
      "Không chỉ là một di tích lịch sử đặc biệt, Cố đô Hoa Lư còn mang vẻ đẹp yên bình và trầm mặc của vùng đất cố đô. Giữa không gian thanh tịnh, tiếng chuông chùa vang vọng cùng những hàng cây cổ thụ xanh mát tạo nên cảm giác bình yên khó tìm thấy ở những đô thị hiện đại.",
      "Đến với Hoa Lư, du khách không chỉ khám phá một điểm đến, mà còn được chạm vào những trang sử hào hùng của dân tộc, nơi khởi đầu cho hành trình hình thành và phát triển của đất nước Việt Nam.",
    ],
    highlights: [
      { number: "01", title: "Đền thờ Vua Đinh Tiên Hoàng", description: "Công trình cổ kính tưởng nhớ vị vua lập nên nhà nước Đại Cồ Việt độc lập." },
      { number: "02", title: "Đền thờ Vua Lê Đại Hành", description: "Dấu ấn triều Tiền Lê, nơi lưu giữ câu chuyện tiếp nối và bảo vệ kinh đô." },
    ],
    galleryEyebrow: "Kỷ nghệ ngàn năm",
    galleryTitle: "Dấu vết kiến trúc Hoa Lư",
    gallery: [
      { src: `${hoaLuBase}/CĐHL 1.jpg`, caption: "Long mạch cố đô" },
      { src: `${hoaLuBase}/CĐHL 2.jpg`, caption: "Mái đền cổ kính" },
      { src: `${hoaLuBase}/CĐHL 3.jpg`, caption: "Dấu ấn thành cổ" },
      { src: `${hoaLuBase}/CĐHL 4.jpg`, caption: "Lối vào di tích" },
      { src: `${hoaLuBase}/CDHL 5.webp`, caption: "Thung lũng Hoa Lư" },
    ],
    closingTitle: "Chạm vào lịch sử",
    closingText: "Bước qua những thành quách phủ rêu phong, ta như nghe tiếng vọng của quá khứ và nhịp thở của vùng đất từng khai mở một chương mới.",
  },
  {
    slug: "bai-dinh",
    layout: "bai-dinh",
    name: "Chùa Bái Đính",
    navName: "BÁI ĐÍNH",
    eyebrow: "Hành trình tìm về miền đất Phật",
    title: "Chùa Bái Đính",
    subtitle: "Quần thể chùa rộng lớn giữa thung lũng, nơi kiến trúc truyền thống hòa cùng cảnh quan kỳ vĩ.",
    heroImage: `${baiDinhBase}/Chùa Bái Đính 1.jpg`,
    featureImage: `${baiDinhBase}/Chùa Bái Đính 2.jpg`,
    storyImage1: "/assets/dia-danh-stories/bai-dinh-story-1.png",
    storyImage2: "/assets/dia-danh-stories/bai-dinh-story-2.png",
    featureCaption: "Nơi sương khói mờ ảo quyện cùng tiếng chuông chùa thanh tịnh.",
    sectionLabel: "Di sản ngàn năm",
    introTitle: "Truyền thuyết động thiêng",
    introParagraphs: [
      "Nằm giữa thung lũng rộng lớn, Chùa Bái Đính là một trong những quần thể chùa lớn nhất Đông Nam Á.",
      "Theo truyền thuyết, thiền sư Nguyễn Minh Không đã tìm thấy động thiêng tại vùng núi Bái Đính và lập chùa để chữa bệnh cứu người.",
      "Không chỉ gây ấn tượng bởi quy mô đồ sộ, nơi đây còn là sự kết hợp hài hòa giữa kiến trúc truyền thống và cảnh quan thiên nhiên kỳ vĩ của vùng đất cố đô.",
    ],
    storyTitle: "Kỷ lục Phật giáo",
    storyParagraphs: [
      "Điểm đặc biệt của Chùa Bái Đính là hệ thống tượng Phật bằng đồng lớn, hành lang La Hán dài hàng trăm mét cùng tháp chuông và bảo tháp uy nghiêm.",
      "Trải qua nhiều thế kỷ, nơi đây dần trở thành một trung tâm Phật giáo quan trọng, thu hút hàng triệu Phật tử và du khách đến chiêm bái mỗi năm.",
      "Mỗi công trình đều mang những giá trị nghệ thuật và tâm linh đặc sắc, phản ánh nét đẹp của văn hóa Phật giáo Việt Nam.",
      "Vào những ngày đầu xuân, lễ hội chùa Bái Đính thu hút hàng vạn du khách thập phương đến cầu bình an, sức khỏe và may mắn cho một năm mới.",
      "Giữa nhịp sống hối hả của thời hiện đại, Chùa Bái Đính giống như một khoảng lặng, nơi con người tìm lại sự cân bằng trong tâm hồn và cảm nhận rõ hơn vẻ đẹp của văn hóa, tín ngưỡng truyền thống Việt Nam.",
    ],
    highlights: [
      { number: "500", title: "Hành lang La Hán", description: "Dãy hành lang dài với hàng trăm tượng La Hán tạo nên nhịp điệu chiêm bái tĩnh tại." },
      { number: "100", title: "Tượng Phật Đồng", description: "Hệ thống tượng lớn tạo dấu ấn về quy mô và kỹ thuật đúc đồng truyền thống." },
      { number: "13", title: "Bảo Tháp Xá Lợi", description: "Công trình tâm linh nổi bật, mở ra tầm nhìn rộng giữa núi non." },
    ],
    galleryEyebrow: "Không gian",
    galleryTitle: "Góc nhìn di sản",
    gallery: [
      { src: `${baiDinhBase}/Chùa Bái Đính 1.jpg`, caption: "Toàn cảnh Bái Đính" },
      { src: `${baiDinhBase}/Chùa Bái Đính 2.jpg`, caption: "Không gian Phật điện" },
      { src: `${baiDinhBase}/Chùa Bái Đính 3.jpg`, caption: "Mái chùa giữa núi" },
      { src: `${baiDinhBase}/Chùa bái đính 4.jpg`, caption: "Hành lang La Hán" },
      { src: `${baiDinhBase}/Chùa Bái Đính 5.jpg`, caption: "Ánh vàng tĩnh lặng" },
    ],
    closingTitle: "Tìm lại sự cân bằng",
    closingText: "Bái Đính đón bạn bằng tiếng chuông chùa thanh tịnh và không gian khoáng đạt của núi rừng.",
  },
  {
    slug: "tam-coc",
    layout: "tam-coc",
    name: "Tam Cốc - Bích Động",
    navName: "TAM CỐC",
    eyebrow: "Vịnh Hạ Long trên cạn",
    title: "Tam Cốc - Bích Động",
    subtitle: "Bức tranh sơn thủy giữa lòng cố đô.",
    heroImage: `${tamCocBase}/TC1.jpg`,
    featureImage: `${tamCocBase}/TC2.jpg`,
    storyImage1: "/assets/dia-danh-stories/tam-coc-story-1.png",
    storyImage2: "/assets/dia-danh-stories/tam-coc-story-2.png",
    featureCaption: "Một nhịp chèo trên sông là một lát cắt của mùa, ánh sáng và ký ức.",
    sectionLabel: "Hành trình di sản",
    introTitle: "Xuôi dòng Ngô Đồng",
    introParagraphs: [
      "Tam Cốc - Bích Động nổi bật với núi đá vôi kỳ vĩ, cánh đồng lúa trải dài và dòng sông Ngô Đồng uốn lượn mềm mại.",
      "Hành trình thường bắt đầu bằng chuyến đò nhỏ xuôi dòng, lần lượt đi qua Hang Cả, Hang Hai và Hang Ba.",
      "Khi con thuyền nhẹ nhàng lướt qua những cánh đồng lúa xanh mướt hoặc vàng óng vào mùa gặt, sự kết hợp giữa ánh sáng, mặt nước và những khối thạch nhũ hàng triệu năm tuổi tạo nên khung cảnh vừa kỳ bí vừa thơ mộng.",
    ],
    storyTitle: "Nam Thiên Đệ Nhị Động",
    storyParagraphs: [
      "Cách Tam Cốc không xa là chùa Bích Động, ngôi chùa cổ hơn 300 năm tuổi được xây dựng dựa lưng vào núi đá.",
      "Những bậc đá rêu phong, mái chùa cổ kính và tiếng chuông ngân giữa núi rừng tạo nên không gian thanh bình và đầy chất thiền.",
      "Từ xa xưa, nơi đây đã được mệnh danh là Nam Thiên Đệ Nhị Động, tức động đẹp thứ hai của trời Nam.",
      "Không chỉ là điểm đến dành cho những người yêu thiên nhiên, Tam Cốc - Bích Động còn là nơi lưu giữ những giá trị văn hóa lâu đời của vùng đất cố đô.",
      "Mỗi mùa trong năm, nơi đây lại khoác lên mình một vẻ đẹp khác nhau, mang đến cho du khách những trải nghiệm khó quên trong hành trình khám phá Ninh Bình.",
    ],
    highlights: [
      { number: "01", title: "Lúa vàng", description: "Tháng 5 - tháng 6 là mùa đồng lúa chuyển vàng rực rỡ." },
      { number: "02", title: "Mùa sen nở", description: "Tháng 6 - tháng 7 là thời điểm mặt nước sáng lên bởi sắc sen." },
      { number: "03", title: "Mùa sương giăng", description: "Sáng sớm mang đến lớp sương mỏng giữa núi và sông." },
    ],
    galleryEyebrow: "Sắc màu Tam Cốc",
    galleryTitle: "Mỗi góc nhìn là một bức tranh",
    gallery: [
      { src: `${tamCocBase}/TC1.jpg`, caption: "Dòng sông giữa mùa lúa" },
      { src: `${tamCocBase}/TC2.jpg`, caption: "Thuyền xuôi Ngô Đồng" },
      { src: `${tamCocBase}/TC4.jpg`, caption: "Núi đá và đồng xanh" },
      { src: `${tamCocBase}/TC5.jpg`, caption: "Bích Động trầm mặc" },
      { src: `${tamCocBase}/TC8.jpg`, caption: "Hoa sen mùa hạ" },
    ],
    closingTitle: "Mỗi mùa một vẻ, mười phần vẹn mười",
    closingText: "Tam Cốc - Bích Động không chỉ là một danh thắng, đó là nơi bạn cảm nhận nhịp điệu thiên nhiên bằng từng mái chèo.",
  },
  {
    slug: "pho-co-hoa-lu",
    layout: "pho-co",
    name: "Phố Cổ Hoa Lư",
    navName: "PHỐ CỔ",
    eyebrow: "Nơi quá khứ và hiện tại giao hòa",
    title: "Phố Cổ Hoa Lư",
    subtitle: "Không gian văn hóa bên hồ Kỳ Lân, rực sáng khi màn đêm buông xuống.",
    heroImage: `${phoCoBase}/PCHL1.jpg`,
    featureImage: `${phoCoBase}/PCHL 2.jpg`,
    storyImage1: "/assets/dia-danh-stories/pho-co-story-1.png",
    storyImage2: "/assets/dia-danh-stories/pho-co-story-2.png",
    featureCaption: "Mái cong, đèn lồng và nhịp phố tạo nên một không gian vừa cổ kính vừa sống động.",
    sectionLabel: "Di sản kiến trúc",
    introTitle: "Giao thoa văn hóa giữa lòng di sản",
    introParagraphs: [
      "Khi màn đêm buông xuống, Phố Cổ Hoa Lư khoác lên mình vẻ đẹp lung linh và đầy sức sống.",
      "Những mái ngói cong, đèn lồng rực rỡ và các công trình lấy cảm hứng kiến trúc Đại Việt tạo nên không gian gần gũi và hoài niệm.",
      "Nằm bên hồ Kỳ Lân, đây là một trong những điểm đến mới nổi của Ninh Bình, được xây dựng với cảm hứng từ kiến trúc truyền thống Đại Việt, tái hiện không gian văn hóa đặc trưng của vùng đất cố đô.",
      "Không giống những khu phố cổ lâu đời hình thành qua hàng trăm năm lịch sử, Phố Cổ Hoa Lư là sự giao thoa giữa nét đẹp truyền thống và hơi thở hiện đại.",
    ],
    storyTitle: "Hương vị Cố Đô",
    storyParagraphs: [
      "Dạo bước trên những con phố nhỏ, du khách có thể thưởng thức cơm cháy, thịt dê núi, miến lươn hoặc khám phá các gian hàng lưu niệm địa phương.",
      "Không khí nhộn nhịp của các quán cà phê, khu chợ đêm và các hoạt động biểu diễn nghệ thuật truyền thống đã biến nơi đây trở thành điểm đến hấp dẫn dành cho cả người dân địa phương lẫn du khách.",
      "Vào những dịp cuối tuần hay lễ hội, Phố Cổ Hoa Lư thường xuyên tổ chức các chương trình biểu diễn văn hóa, múa lân, hát chèo và nhiều hoạt động nghệ thuật dân gian đặc sắc.",
      "Những âm thanh quen thuộc của văn hóa truyền thống hòa quyện cùng ánh đèn lung linh bên hồ Kỳ Lân đã tạo nên một bầu không khí rất riêng mà khó nơi nào có được.",
      "Đối với nhiều du khách, Phố Cổ Hoa Lư không chỉ đơn thuần là một điểm vui chơi về đêm mà còn là nơi lưu giữ những khoảnh khắc đáng nhớ trong hành trình khám phá Ninh Bình.",
      "Khép lại hành trình tại Phố Cổ Hoa Lư, mỗi du khách không chỉ mang về những bức ảnh đẹp mà còn mang theo những câu chuyện, những ký ức và những dấu ấn đặc biệt của vùng đất cố đô.",
    ],
    highlights: [
      { number: "01", title: "Cơm cháy Thiên Hương", description: "Món quà giòn thơm, gói gọn hương vị Ninh Bình." },
      { number: "02", title: "Thịt dê núi Hoa Lư", description: "Hương vị đặc trưng của vùng núi đá, thường xuất hiện trong trải nghiệm ẩm thực địa phương." },
      { number: "03", title: "Quà tặng thủ công", description: "Những món lưu niệm nhỏ giúp du khách mang về ký ức của chuyến đi." },
    ],
    galleryEyebrow: "Khoảnh khắc Phố Cổ",
    galleryTitle: "Ánh đèn bên hồ Kỳ Lân",
    gallery: [
      { src: `${phoCoBase}/PCHL1.jpg`, caption: "Phố cổ về đêm" },
      { src: `${phoCoBase}/PCHL 2.jpg`, caption: "Không gian mái ngói" },
      { src: `${phoCoBase}/PCHL 3.jpg`, caption: "Đèn lồng bên hồ" },
      { src: `${phoCoBase}/IMG_1021.JPG`, caption: "Nhịp phố bên nước" },
      { src: `${phoCoBase}/IMG_1024.JPG`, caption: "Ánh đèn vàng" },
      { src: `${phoCoBase}/IMG_1028.JPG`, caption: "Cầu soi bóng" },
    ],
    closingTitle: "Lưu giữ hành trình - Chạm đến di sản",
    closingText: "Hãy để Phố Cổ Hoa Lư giữ lại trong tim bạn bằng những khoảnh khắc nhiệm màu của hành trình.",
  },
  {
    slug: "hang-mua",
    layout: "hang-mua",
    name: "Hang Múa",
    navName: "HANG MÚA",
    eyebrow: "Sắc Cố Đô - Ninh Bình",
    title: "Đỉnh cao di sản",
    subtitle: "Chạm tới vẻ đẹp của Ninh Bình từ trên cao.",
    heroImage: `${hangMuaBase}/HM1.jpg`,
    featureImage: `${hangMuaBase}/HM2.jpg`,
    storyImage1: "/assets/dia-danh-stories/hang-mua-story-1.png",
    storyImage2: "/assets/dia-danh-stories/hang-mua-story-2.png",
    featureCaption: "Tương truyền vua Trần từng đến đây nghỉ ngơi và thưởng thức điệu múa của cung nữ.",
    sectionLabel: "Huyền thoại cổ kính",
    introTitle: "Truyền thuyết điệu múa",
    introParagraphs: [
      "Ẩn mình dưới chân núi Ngọa Long, Hang Múa là một trong những điểm đến được yêu thích nhất tại Ninh Bình.",
      "Tương truyền thời nhà Trần, các vị vua thường đến đây nghỉ ngơi và thưởng thức điệu múa của cung nữ, từ đó hình thành tên gọi Hang Múa.",
      "Không chỉ nổi tiếng với khung cảnh ngoạn mục nhìn từ trên cao, nơi đây còn mang trong mình những câu chuyện lịch sử gắn liền với vùng đất cố đô ngàn năm văn hiến.",
      "Dù trải qua nhiều biến động của thời gian, vùng đất này vẫn giữ được vẻ đẹp nguyên sơ với những dãy núi đá vôi hùng vĩ bao quanh cánh đồng Tam Cốc rộng lớn.",
    ],
    storyTitle: "Chinh phục 486 bậc đá",
    storyParagraphs: [
      "Hành trình lên đỉnh Ngọa Long có chút thử thách, nhưng phần thưởng là toàn cảnh dòng sông Ngô Đồng, cánh đồng Tam Cốc và các dãy núi đá vôi trùng điệp.",
      "Để lên tới đỉnh núi Ngọa Long, du khách sẽ chinh phục gần 500 bậc đá được xây dựng theo kiến trúc mô phỏng Vạn Lý Trường Thành.",
      "Từ trên cao, toàn bộ dòng sông Ngô Đồng mềm mại, những cánh đồng lúa trải dài cùng các dãy núi đá vôi hiện lên như một bức tranh thủy mặc sống động.",
      "Đặc biệt, vào mùa lúa chín từ tháng 5 đến tháng 6, Hang Múa trở thành một trong những địa điểm ngắm cảnh đẹp nhất Việt Nam.",
      "Không chỉ là một địa điểm check-in nổi tiếng, Hang Múa còn mang đến cho du khách cảm giác chinh phục, hòa mình với thiên nhiên và tận hưởng vẻ đẹp thanh bình của vùng đất cố đô.",
    ],
    highlights: [
      { number: "01", title: "Vạn Lý Trường Thành thu nhỏ", description: "Bậc đá uốn lượn theo sườn núi tạo nên hành trình chinh phục giàu cảm xúc." },
      { number: "02", title: "Hơi thở của đá núi", description: "Mỗi bậc chân là một nhịp chạm vào thời gian." },
      { number: "03", title: "Phần thưởng của người bền bỉ", description: "Tầm nhìn toàn cảnh mở ra như một bức tranh thủy mặc." },
    ],
    stats: [
      { value: "486", label: "bậc đá Ngọa Long" },
      { value: "~25ph", label: "thời gian leo núi" },
      { value: "800m", label: "độ cao so với mực nước biển" },
    ],
    galleryEyebrow: "Góc nhìn từ mây ngàn",
    galleryTitle: "Đỉnh cao di sản",
    gallery: [
      { src: `${hangMuaBase}/HM1.jpg`, caption: "Đường lên Ngọa Long" },
      { src: `${hangMuaBase}/HM2.jpg`, caption: "Hang Múa trong truyền thuyết" },
      { src: `${hangMuaBase}/HM3.jpg`, caption: "Tầm nhìn xuống Tam Cốc" },
      { src: `${hangMuaBase}/HM4.jpg`, caption: "Bậc đá uốn lượn" },
      { src: `${hangMuaBase}/HM7.jpg`, caption: "Núi non trùng điệp" },
    ],
    closingTitle: "Cảm giác của sự chinh phục",
    closingText: "Khi đứng trên đỉnh Ngọa Long, mọi mệt mỏi nhường chỗ cho niềm tự hào và sự bình yên của vùng đất cố đô.",
  },
];

export function getHeritageDestination(slug) {
  return heritageDestinations.find((destination) => destination.slug === slug);
}
